<?php
function mission_start()
{
	return array(
	array(
		array(
			'monster_id'=>'1',
			'kill_num'=>'6'
		),
		array(
			'monster_id'=>'49',
			'kill_num'=>'6'
		),
		array(
			'monster_id'=>'19',
			'kill_num'=>'6'
		),
		array(
			'monster_id'=>'104',
			'kill_num'=>'6'
		),
		array(
			'monster_id'=>'22',
			'kill_num'=>'5'
		),
		array(
			'monster_id'=>'26',
			'kill_num'=>'5'
		),
		array(
			'monster_id'=>'36',
			'kill_num'=>'4'
		),
		array(
			'monster_id'=>'57',
			'kill_num'=>'4'
		)
	),
	array(
		array(
		'a_id'=>array(),
		'd_body_id'=>array(),
		'd_foot_id'=>array(),
		'd_hand_id'=>array(),
		'd_head_id'=>array(),
		'd_item_id'=>array(),
		'd_stone_id'=>array(),
		'd_honor_id'=>array('1304*1'),
		'd_plus_id'=>array()
		),
		array(
		'a_id'=>array(),
		'd_body_id'=>array(),
		'd_foot_id'=>array(),
		'd_hand_id'=>array(),
		'd_head_id'=>array(),
		'd_item_id'=>array(),
		'd_stone_id'=>array(),
		'd_honor_id'=>array('1305*1'),
		'd_plus_id'=>array()
		),
		array(
		'a_id'=>array(),
		'd_body_id'=>array(),
		'd_foot_id'=>array(),
		'd_hand_id'=>array(),
		'd_head_id'=>array(),
		'd_item_id'=>array(),
		'd_stone_id'=>array(),
		'd_honor_id'=>array('1306*1'),
		'd_plus_id'=>array()
		),
		array(
		'a_id'=>array(),
		'd_body_id'=>array(),
		'd_foot_id'=>array(),
		'd_hand_id'=>array(),
		'd_head_id'=>array(),
		'd_item_id'=>array(),
		'd_stone_id'=>array(),
		'd_honor_id'=>array('2222*1'),
		'd_plus_id'=>array()
		),
		array(
		'a_id'=>array(),
		'd_body_id'=>array(),
		'd_foot_id'=>array(),
		'd_hand_id'=>array(),
		'd_head_id'=>array(),
		'd_item_id'=>array(),
		'd_stone_id'=>array(),
		'd_honor_id'=>array('1307*1'),
		'd_plus_id'=>array()
		)
	),
	'mission_type'=>'1'
	);
}
function mission_body($user_id,$m_id)
{
}
function mission_end($user_id,$m_id)
{

}
?>